py_library(
    name = "package_b",
    srcs = [
        "module3.py",
    ],
    imports = ["../.."],
    # imports = ["//custom_project_root"],
    srcs_version = "PY3",
    visibility = ["//custom_project_root:__subpackages__"],
)
