py_library(
    name = "package_a",
    srcs = [
        "module1.py",
        "module2.py",
    ],
    imports = [".."],
    # imports = ["//custom_project_root"],
    srcs_version = "PY3",
    visibility = ["//custom_project_root:__subpackages__"],
)
